-- =========================================
-- DATABASE SETUP
-- =========================================

CREATE DATABASE customer_behavior;
USE customer_behavior;

-- Preview Data
SELECT * FROM customer;


-- =========================================
-- 1. Total Revenue by Gender
-- =========================================

-- Q: What is the total revenue generated by male vs female customers?

SELECT 
    gender, 
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;


-- =========================================
-- 2. High Spending Customers with Discount
-- =========================================

-- Q: Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id, 
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
        SELECT AVG(purchase_amount) FROM customer
    );


-- =========================================
-- 3. Top 5 Products by Average Rating
-- =========================================

-- Q: Which are the top 5 products with highest average review ratings?

SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;


-- =========================================
-- 4. Average Purchase by Shipping Type
-- =========================================

-- Q: Compare the average purchase amount between Standard and Express shipping

SELECT 
    shipping_type, 
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- =========================================
-- 5. Subscription Spending Analysis
-- =========================================

-- Q: Do subscribed customers spend more?

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;


-- =========================================
-- 6. Top 5 Products by Discount Usage %
-- =========================================

-- Q: Which 5 products have the highest percentage of purchases with discount applied?

SELECT 
    item_purchased, 
    ROUND(
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 
    2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- =========================================
-- 7. Customer Segmentation
-- =========================================

-- Q: Segment customers into New, Returning, and Loyal based on previous purchases

WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT 
    customer_segment, 
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- =========================================
-- 8. Top 3 Products per Category
-- =========================================

-- Q: What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT 
        category, 
        item_purchased, 
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;


-- =========================================
-- 9. Repeat Buyers vs Subscription
-- =========================================

-- Q: Are repeat buyers (more than 5 purchases) likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- =========================================
-- 10. Revenue by Age Group
-- =========================================

-- Q: What is the revenue contribution by each age group?

SELECT 
    age_group, 
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group;
